---
apiVersion: v1
kind: Service
metadata:
  name: cx-php-laravel
  labels:
    app: cx-php-laravel
spec:
  selector:
    app: cx-php-laravel
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-php-laravel
  namespace: default
  labels:
    app: cx-php-laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-php-laravel
  template:
    metadata:
      labels:
        app: cx-php-laravel
    spec:
      containers:
        - name: cx-php-laravel
          image: public.ecr.aws/w3s4j9x9/microservices-demo:php-laravel
          imagePullPolicy: Always
          workingDir: /app/otel-php-laravel-basic-example
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: OTEL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: "true"
            - name: OTEL_SERVICE_NAME
              value: cx-php-laravel
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: cx.application.name=cx-php-laravel,cx.subsystem.name=cx-php-laravel
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_IP):4318
            - name: OTEL_PROPAGATORS
              value: "baggage,tracecontext"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          command: ["php"]
          args: ["artisan", "serve", "--host=0.0.0.0", "--port=8000"]
