---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-node-autogen
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-node-autogen
  template:
    metadata:
      labels:
        name: cx-node-autogen
    spec:
      containers:
      - name: cx-node-autogen
        image: public.ecr.aws/w3s4j9x9/microservices-demo:node
        imagePullPolicy: Always
        workingDir: /home/code
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-node-autogen
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: otlp
        - name: OTEL_NODE_RESOURCE_DETECTORS
          value: "env,host,os"
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-node-autogen,cx.subsystem.name=cx-node-autogen
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4318
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]