apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-java
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-java
  template:
    metadata:
      labels:
        name: cx-java
    spec:
      containers:
      - name: cx-java
        image: public.ecr.aws/w3s4j9x9/autoinject-demo:java-autoinject
        imagePullPolicy: Always
        workingDir: /home/code
        env:
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]