apiVersion: v1
kind: Service
metadata:
  name: cx-py
spec:
  selector:
    name: cx-py
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-py
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-py
  template:
    metadata:
      labels:
        name: cx-py
    spec:
      containers:
      - name: cx-py
        image: public.ecr.aws/w3s4j9x9/autoinject-demo:py-autoinject
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
