site_name: Coralogix Workshops
site_url: http://coralogix.github.io
site_author: Coralogix
site_description: Coralogix workshops for observability
repo_url: http://github.com/coralogix/workshops
copyright: Copyright Coralogix. All rights reserved.

theme:
  name: material
  palette:
    primary: green
  logo: images/horizontal.png
  favicon: images/favicon.png
  font:
    text: "Nunito Sans"
    code: "Jetbrains mono"
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - Home: index.md
  - Prerequisites: prereqs.md
  - Coralogix + OpenTelemetry: 
      - Getting Started Overview: https://coralogix.com/docs/opentelemetry/getting-started/
  - Workshops:
      - Microservices + Otel Collector: otel/microservices/index.md
      - Otel Collector Examples:
          - Prometheus Collector Config: otel/prometheus/index.md
          - MySQL Metrics + Query Performance: otel/mysql/index.md
          - Redis Metrics: otel/redis/index.md
      - Hosted Container Environments:
          - AWS ECS Fargate (PHP): otel/ecs-fargate/index.md
          - AWS ECS EC2 (Python/Node.js): otel/ecs-ec2/index.md
      - Instrumentation Examples:
          - Autogenerators (.NET, Node.js, Java, Python): otel/autogenerators/index.md
          - Manual Instrumentation: otel/manual-instrumentation/index.md
      - Kubernetes Specific:
          - Auto Tracing Injection: otel/autoinjection/index.md
          - eBPF (No Instrumentation): otel/ebpf/index.md
      - Real User Monitoring (RUM): rum/index.md
      - Official OpenTelemetry Demo: otel/opentelemetrydemo/index.md
  - Live Demo Tools: https://github.com/coralogix/workshops/tree/master/livedemotools
