site_name: Coralogix Workshops
site_url: http://coralogix.github.io
site_author: Coralogix
site_description: Coralogix workshops for observability
repo_url: http://github.com/coralogix/workshops
copyright: Copyright Coralogix. All rights reserved.

theme:
  name: material
  palette:
    primary: green
  logo: images/horizontal.png
  favicon: images/favicon.png
  font:
    text: "Nunito Sans"
    code: "Jetbrains mono"
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - toc.follow

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - Home: index.md
  - Prerequisites: prereqs.md