AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ClusterName: { Type: String }
  CxNodeImage: { Type: String, Default: public.ecr.aws/w3s4j9x9/microservices-demo:node }
  CxNodeMemory: { Type: Number, Default: 512 }
  CxNodeCPU: { Type: Number, Default: 256 }

Resources:
  CxNodeAutoGenTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cx-node-autogen
      NetworkMode: host
      RequiresCompatibilities: [EC2]
      Cpu: !Ref CxNodeCPU
      Memory: !Ref CxNodeMemory
      ContainerDefinitions:
        - Name: cx-node-autogen
          Image: !Ref CxNodeImage
          Memory: !Ref CxNodeMemory
          Cpu: !Ref CxNodeCPU
          Environment:
            - { Name: OTEL_SERVICE_NAME, Value: cx-node-autogen }
            - { Name: OTEL_TRACES_EXPORTER, Value: otlp }
            - { Name: OTEL_METRICS_EXPORTER, Value: otlp }
            - { Name: OTEL_NODE_RESOURCE_DETECTORS, Value: "env,host,os" }
            - { Name: NODE_OPTIONS, Value: "--require @opentelemetry/auto-instrumentations-node/register" }
            - { Name: OTEL_RESOURCE_ATTRIBUTES, Value: "application.name=cx-node-autogen,api.name=cx-node-autogen,cx.application.name=cx-node-autogen,cx.subsystem.name=cx-node-autogen" }
            - { Name: NODE_TEST_URL, Value: api.github.com }
            - { Name: OTEL_LOG_LEVEL, Value: all }
            - { Name: OTEL_EXPORTER_OTLP_ENDPOINT, Value: http://localhost:4318 }
          EntryPoint: ["sh", "-c", "sh ./run-client.sh"]       
          # LogConfiguration:
          #   LogDriver: awslogs
          #   Options:
          #     awslogs-group: slerner-ecs-logs
          #     awslogs-region: us-east-2  
          #     awslogs-stream-prefix: ecs

  CxNodeAutoGenService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref ClusterName
      LaunchType: EC2
      ServiceName: cx-node-autogen-service
      SchedulingStrategy: DAEMON
      DeploymentConfiguration: { MaximumPercent: 100, MinimumHealthyPercent: 0 }
      TaskDefinition: !Ref CxNodeAutoGenTaskDefinition