ecs-cli up \
    --region YOURREGIONHERE \
    --cluster YOURCLUSTERNAMEHERE \
    --keypair YOURKEYPAIRHERE \
    --capability-iam \
    --instance-type t2.xlarge \
    --size 1 \
    --security-group YOURSGHERE \
    --vpc YOURVPCHERE \
    --subnets YOURSUBNET1HERE, YOURSUBNET2HERE \
    --force