AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ClusterName: { Type: String }
  NodeImage: { Type: String, Default: public.ecr.aws/w3s4j9x9/microservices-demo:node }
  NodeMemory: { Type: Number, Default: 512 }
  NodeCPU: { Type: Number, Default: 256 }

Resources:
  NodeAutoGenTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cx-node-autogen
      NetworkMode: host
      RequiresCompatibilities: [EC2]
      Cpu: !Ref NodeCPU
      Memory: !Ref NodeMemory
      # DeletionPolicy: Delete  # Add this line to specify the deletion policy
      ContainerDefinitions:
        - Name: node-autogen
          Image: !Ref NodeImage
          Memory: !Ref NodeMemory
          Cpu: !Ref NodeCPU
          Environment:
            - { Name: ECS_ENABLE_CONTAINER_METADATA, Value: true }
            - { Name: OTEL_SERVICE_NAME, Value: node-autogen }
            - { Name: OTEL_TRACES_EXPORTER, Value: otlp }
            - { Name: OTEL_METRICS_EXPORTER, Value: otlp }
            # - { Name: OTEL_NODE_RESOURCE_DETECTORS, Value: "env,host,os" }
            - { Name: NODE_OPTIONS, Value: "--require @opentelemetry/auto-instrumentations-node/register" }
            - { Name: OTEL_RESOURCE_ATTRIBUTES, Value: "cx.application.name=cx-node-autogen,cx.subsystem.name=cx-node-autogen" }
            - { Name: NODE_TEST_URL, Value: api.github.com }
            - { Name: OTEL_LOG_LEVEL, Value: error }
            - { Name: OTEL_EXPORTER_OTLP_ENDPOINT, Value: http://localhost:4318 }
          EntryPoint: ["sh", "-c", "sh ./entrypoint.sh"]       
          # EntryPoint: ["sh", "-c", "while true; do sleep 30; done;"]      

  NodeAutoGenService:
    Type: 'AWS::ECS::Service'
    Properties:
      Cluster: !Ref ClusterName
      LaunchType: EC2
      ServiceName: node-autogen-service
      SchedulingStrategy: DAEMON
      DeploymentConfiguration: { MaximumPercent: 100, MinimumHealthyPercent: 0 }
      TaskDefinition: !Ref NodeAutoGenTaskDefinition