# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks

extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

connectors:
  spanmetrics:
    namespace: ""
    histogram:
      explicit:
        buckets:
          - 1ms
          - 4ms
          - 10ms
          - 20ms
          - 50ms
          - 100ms
          - 200ms
          - 500ms
          - 1s
          - 2s
          - 5s
      dimensions:
        - name: http.method
        - name: cgx.transaction
        - name: cgx.transaction.root
        - name: status_code
        - name: db.namespace
        - name: db.operation.name
        - name: db.collection.name
        - name: db.system
        - name: http.response.status_code
        - name: rpc.grpc.status_code
        - name: service.version
    exemplars:
      enabled: true
    dimensions_cache_size: 1000
    aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"    
    metrics_flush_interval: '30s'
    # metricsExpiration: 5m
    events:
      enabled: true
      dimensions:
        - name: exception.type
        - name: exception.message

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 10s
    process:
      enabled: true
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      process:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 85
    spike_limit_percentage: 25
  batch:
  resourcedetection/env:
    detectors: ["system", "env"]
    system:
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: true
  resourcedetection/ec2:
    detectors: ["ec2" ]
    ec2:
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: true

exporters:
  debug:
    verbosity: detailed

  coralogix:
    # The Coralogix domain
    domain: "YOURDOMAINHERE i.e. cx498.coralogix.com"
    # Your Coralogix private key is sensitive
    private_key: "YOURKEYHERE"

    # (Optional) Ordered list of Resource attributes that are used for Coralogix
    # AppName and SubSystem values. The first non-empty Resource attribute is used.
    # Example: application_name_attributes: ["k8s.namespace.name", "service.namespace"]
    # Example: subsystem_name_attributes: ["k8s.deployment.name", "k8s.daemonset.name", "service.name"]
    application_name_attributes:
    - "service.namespace"
    subsystem_name_attributes:
    - "service.name"

    # Traces, Metrics and Logs emitted by this OpenTelemetry exporter 
    # are tagged in Coralogix with the default application and subsystem constants.
    application_name: "demo-server"
    subsystem_name: "demo-server"

    # (Optional) Timeout is the timeout for every attempt to send data to the backend.
    timeout: 30s

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection/env, resourcedetection/ec2, batch]
      exporters: [coralogix, spanmetrics]

    metrics:
      receivers: [otlp, prometheus, hostmetrics, spanmetrics]
      processors: [memory_limiter, resourcedetection/env, resourcedetection/ec2, batch]
      exporters: [coralogix]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, resourcedetection/env, resourcedetection/ec2, batch]
      exporters: [coralogix]

  extensions: [health_check, pprof, zpages]