apiVersion: v1
kind: Service
metadata:
  name: cx-autogen-py-jaeger
spec:
  selector:
    name: cx-autogen-py-jaeger
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-autogen-py-jaeger
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-autogen-py-jaeger
  template:
    metadata:
      labels:
        name: cx-autogen-py-jaeger
    spec:
      containers:
        - name: cx-autogen-py-jaeger
          image: public.ecr.aws/w3s4j9x9/microservices-demo:py-autogen-jaeger
          imagePullPolicy: Always
          workingDir: /home/code
          ports:
            - name: http
              containerPort: 5000
          env:
            - name: OTEL_EXPORTER_JAEGER_AGENT_HOST
              value: "jaeger-agent.default.svc.cluster.local"  # Points to standalone Jaeger Agent service
            - name: OTEL_EXPORTER_JAEGER_AGENT_PORT
              value: "6831"
            - name: OTEL_SERVICE_NAME
              value: cx-autogen-py-jaeger
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: cx.application.name=cx-autogen-py-jaeger,cx.subsystem.name=cx-autogen-py-jaeger
