apiVersion: v1
kind: Service
metadata:
  name: cx-py-1
spec:
  selector:
    name: cx-py-1
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-py-1
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-py-1
  template:
    metadata:
      labels:
        name: cx-py-1
    spec:
      containers:
      - name: cx-py-1
        image: public.ecr.aws/w3s4j9x9/microservices-demo:py-autogen
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-py-1
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-py-1,cx.subsystem.name=cx-py-1
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
---
apiVersion: v1
kind: Service
metadata:
  name: cx-py-2
spec:
  selector:
    name: cx-py-2
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-py-2
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-py-2
  template:
    metadata:
      labels:
        name: cx-py-2
    spec:
      containers:
      - name: cx-py-2
        image: public.ecr.aws/w3s4j9x9/microservices-demo:py-autogen
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-py-2
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-py-2,cx.subsystem.name=cx-py-2
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
