---
# Python Requests Deployment One Shot Bad URL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-shopping-cart-reqs
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-shopping-cart-reqs
  template:
    metadata:
      labels:
        name: cx-shopping-cart-reqs
    spec:
      containers:
      - name: cx-shopping-cart-reqs
        image: public.ecr.aws/w3s4j9x9/microservices-demo:python
        imagePullPolicy: Always
        workingDir: /home/code/k8s
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-shopping-cart-reqs
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "application.name=cx-shopping-cart-reqs,api.name=cx-shopping-cart-reqs,cx.application.name=cx-shopping-cart-reqs,cx.subsystem.name=cx-shopping-cart-reqs"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
        # - name: OTEL_PYTHON_LOG_CORRELATION
        #   value: "true"
        # - name: OTEL_PYTHON_LOG_LEVEL
        #   value: "debug"
        # - name: OTEL_PYTHON_LOG_FORMAT
        #   value: OTEL_PYTHON_LOG_FORMAT="%(asctime)s %(levelname)s [%(name)s] [%(filename)s:%(lineno)d] trace_id=%(otelTraceID)s - %(message)s"
        - name: PYTHON_TEST_URLGOOD
          value: "BAD"
        - name: PYTHON_TEST_URL
          value: http://cx-payment-gateway-flask:5000
        - name: PYTHON_ONESHOT
          value: "YES"
        command: ["/bin/sh"]
        args: ["start-reqs-envurl-otel.sh"]
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]