---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-node-autogen
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-node-autogen
  template:
    metadata:
      labels:
        name: cx-node-autogen
    spec:
      containers:
      - name: cx-node-autogen
        image: public.ecr.aws/w3s4j9x9/microservices-demo:node
        imagePullPolicy: Always
        workingDir: /home/code
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-node-autogen
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: application.name=cx-node-autogen,api.name=cx-node-autogen,cx.application.name=cx-node-autogen,cx.subsystem.name=cx-node-autogen
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
        - name: NODE_TEST_URL
          value: api.github.com
        command: ["/bin/sh"]
        args: ["run-client.sh"]
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]