FROM python:slim
RUN mkdir /home/code
COPY app.py /home/code/
COPY entrypoint.sh /home/code/
WORKDIR /home/code
RUN apt -y update && \
    export PATH="$HOME/.local/bin:$PATH" && \
    pip install --upgrade pip && \
    pip install requests "Flask <3" "Werkzeug <3" && \
    pip install opentelemetry-distro==0.41b0 opentelemetry-exporter-otlp==1.20.0 && \
    # pip install opentelemetry-distro opentelemetry-exporter-otlp && \
    opentelemetry-bootstrap -a install && \
    apt -y autoremove && apt-get -y autoclean
# apt install -y dnsutils && \
# apt install -y util-linux && \
# apt install -y coreutils