FROM python:slim
RUN mkdir /home/code
COPY ./apps/*.py /home/code/
COPY ./k8s/*.sh /home/code/
COPY ./setup/requirements.txt /home/code/
WORKDIR /home/code
RUN apt -y update && \
    export PATH="$HOME/.local/bin:$PATH" && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install opentelemetry-distro \
    opentelemetry-instrumentation \
    opentelemetry-exporter-otlp \
    opentelemetry-instrumentation-logging && \
    opentelemetry-bootstrap -a install && \
    apt -y autoremove && apt-get -y autoclean
EXPOSE 5000
# apt install -y curl
# apt install -y dnsutils && \
# apt install -y util-linux && \
# apt install -y coreutils && \
