# extensions:
#   health_check:
#   pprof:
#     endpoint: 0.0.0.0:1777
#   zpages:
#     endpoint: 0.0.0.0:55679
receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      memory:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

processors:
  batch: {}
  memory_limiter:
    check_interval: 5s
    limit_percentage: 80
    spike_limit_percentage: 25
  resourcedetection/env:
    detectors:
    - system
    - env
    override: false
    timeout: 2s

exporters:
  logging:
    verbosity: detailed
  coralogix:
    # The Coralogix traces ingress endpoint
    traces:
      endpoint: "YOURDOMAINHERE i.e. ingress.coralogix.us:443"
    metrics:
      endpoint: "YOURDOMAINHERE i.e. ingress.coralogix.us:443"
    logs:
      endpoint: "YOURDOMAINHERE i.e. ingress.coralogix.us:443"

    # Your Coralogix private key is sensitive
    private_key: "YOURKEYHERE"

    # (Optional) Ordered list of Resource attributes that are used for Coralogix
    # AppName and SubSystem values. The first non-empty Resource attribute is used.
    # Example: application_name_attributes: ["k8s.namespace.name", "service.namespace"]
    # Example: subsystem_name_attributes: ["k8s.deployment.name", "k8s.daemonset.name", "service.name"]
    application_name_attributes:
    - "service.namespace"
    subsystem_name_attributes:
    - "service.name"

    # Traces, Metrics and Logs emitted by this OpenTelemetry exporter 
    # are tagged in Coralogix with the default application and subsystem constants.
    application_name: "MyBusinessEnvironment"
    subsystem_name: "MyBusinessSystem"

    # (Optional) Timeout is the timeout for every attempt to send data to the backend.
    timeout: 30s

service:

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [coralogix]
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch, memory_limiter, resourcedetection/env]
      exporters: [coralogix]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [coralogix]
  telemetry:
    metrics:
      address: localhost:8888

  # extensions: [health_check, pprof, zpages]