FROM node:python-slim
RUN mkdir /home/code
COPY app.py /home/code/
COPY entrypoint.sh /home/code/
WORKDIR /home/code
RUN apt -y update && \
RUN apt -y update && \
    export PATH="$HOME/.local/bin:$PATH" && \
    pip install --upgrade pip && \
    pip install requests && \
    pip install install opentelemetry-distro==0.41b0 opentelemetry-exporter-otlp==1.20.0 \
    apt -y autoremove && apt-get -y autoclean
# apt install -y dnsutils && \
# apt install -y util-linux && \
# apt install -y coreutils