apiVersion: v1
kind: Service
metadata:
  name: cx-mainapp-php
spec:
  selector:
    name: cx-mainapp-php
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-mainapp-php
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-mainapp-php
  template:
    metadata:
      labels:
        name: cx-mainapp-php
    spec:
      containers:
        - name: cx-mainapp-php
          image: public.ecr.aws/w3s4j9x9/microservices-demo:php-autogen
          imagePullPolicy: Always
          workingDir: /home/code
          ports:
            - name: http-main
              containerPort: 8080
            - name: http-subapp
              containerPort: 8081
          env:
            - name: OTEL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_SERVICE_NAME
              value: cx-mainapp-php
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: cx.application.name=cx-mainapp-php,cx.subsystem.name=cx-mainapp-php
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_IP):4318  # Adjust if your collector uses a different IP/port
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: "true"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_PROPAGATORS
              value: "tracecontext,baggage"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          # Override entrypoint to use `entrypointmainapp.sh` for both apps
          command: [ "/bin/bash", "/home/code/entrypointmainapp.sh" ]