apiVersion: v1
kind: Service
metadata:
  name: cx-autogen-php
spec:
  selector:
    name: cx-autogen-php
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-autogen-php
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-autogen-php
  template:
    metadata:
      labels:
        name: cx-autogen-php
    spec:
      containers:
      - name: cx-autogen-php
        image: public.ecr.aws/w3s4j9x9/microservices-demo:php-autogen
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-autogen-php
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-autogen-php,cx.subsystem.name=cx-autogen-php
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4318
        - name: OTEL_PHP_AUTOLOAD_ENABLED
          value: "true"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_PROPAGATORS
          value: "baggage,tracecontext"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]