---
### Flask Server Service
apiVersion: v1
kind: Service
metadata:
  name: cx-payment-gateway-flask
spec:
  selector:
    name: cx-payment-gateway-flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
# Flask Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-payment-gateway-flask
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-payment-gateway-flask
  template:
    metadata:
      labels:
        name: cx-payment-gateway-flask
    spec:
      containers:
      - name: cx-payment-gateway-flask
        image: public.ecr.aws/w3s4j9x9/microservices-demo:python
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_SERVICE_NAME
          value: cx-payment-gateway-flask
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-payment-gateway-flask,cx.subsystem.name=cx-payment-gateway-flask
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://$(OTEL_IP):4317
        # - name: OTEL_PYTHON_LOG_CORRELATION
        #   value: "true"
        # - name: OTEL_PYTHON_LOG_LEVEL
        #   value: "debug"
        - name: REDIS_SERVICE_HOST
          value: cx-redis
        command: ["/bin/sh"]
        args: ["start-flask-redis-otel.sh"]
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: cx-redis
  namespace: default
spec:
  selector:
    name: cx-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-redis
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-redis
  replicas: 1
  template:
    metadata:
      labels:
        name: cx-redis
    spec:
      containers:
      - name: cx-redis
        image: public.ecr.aws/w3s4j9x9/microservices-demo:redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]