extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
  filelog:
    include: [ path to your log file *.log ]
    start_at: beginning

  opencensus:

  # Collect own metrics
  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jaeger:
    protocols:
      grpc:
      thrift_binary:
      thrift_compact:
      thrift_http:

  zipkin:

processors:
  resourcedetection:
    detectors: [system]
    system:
      hostname_sources: ["os"]
  batch:

exporters:
  logging:
    verbosity: detailed
  coralogix:
    # The Coralogix domain
    domain: "your-Coralogix-Domain-Here"
    # Your Coralogix private key is sensitive
    private_key: "xxx"

    # (Optional) Ordered list of Resource attributes that are used for Coralogix
    # AppName and SubSystem values. The first non-empty Resource attribute is used.
    # Example: application_name_attributes: ["k8s.namespace.name", "service.namespace"]
    # Example: subsystem_name_attributes: ["k8s.deployment.name", "k8s.daemonset.name", "service.name"]
    application_name_attributes:
    - "service.namespace"
    subsystem_name_attributes:
    - "service.name"

    # Traces, Metrics and Logs emitted by this OpenTelemetry exporter 
    # are tagged in Coralogix with the default application and subsystem constants.
    application_name: "MyBusinessEnvironment"
    subsystem_name: "MyBusinessSystem"

    # (Optional) Timeout is the timeout for every attempt to send data to the backend.
    timeout: 30s
  
  # use this section instead of the Coralogix exporter if not using a contrib version of the otel collector
  # otlp:
  #   endpoint: "<your coralogix ingress here>:443"
  #   headers:
  #     "Authorization": "<your coralogix key here>"
  #     "CX-Application-Name": "<your coralogix app name here>"
  #     "CX-Subsystem-Name": "<your coralogix subystemname name here>"
  #     ApplicationName: "<your application name here>"
  #     ApiName: "<your api name here>"

service:

  pipelines:

    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      # exporters: [otlp]
      exporters: [coralogix]

    metrics:
      receivers: [otlp, opencensus, prometheus]
      processors: [resourcedetection, batch]
      # exporters: [otlp]
      exporters: [coralogix]

    logs:
      receivers: [otlp]
      processors: [resourcedetection,batch]
      # exporters: [otlp]
      exporters: [coralogix]

  extensions: [health_check, pprof, zpages]
