---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: default
  labels:
    app: jaeger-agent
spec:
  selector:
    app: jaeger-agent
  ports:
    - name: jg-compact
      port: 6831
      protocol: UDP
      targetPort: 6831
    - name: jg-binary
      port: 6832
      protocol: UDP
      targetPort: 6832
    - name: zk-thrift
      port: 5775
      protocol: UDP
      targetPort: 5775
    - name: rest-config
      port: 5778
      protocol: TCP
      targetPort: 5778
    - name: admin-http
      port: 14271
      protocol: TCP
      targetPort: 14271
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-agent
  namespace: default
  labels:
    app: jaeger-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger-agent
  template:
    metadata:
      labels:
        app: jaeger-agent
    spec:
      containers:
        - name: jaeger-agent
          image: jaegertracing/jaeger-agent:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5775
              name: zk-thrift
              protocol: UDP
            - containerPort: 5778
              name: rest-config
              protocol: TCP
            - containerPort: 6831
              name: jg-compact
              protocol: UDP
            - containerPort: 6832
              name: jg-binary
              protocol: UDP
            - containerPort: 14271
              name: admin-http
              protocol: TCP
          args:
            - "--reporter.grpc.host-port=jaeger-collector.jaeger.svc.cluster.local:14250"
            - "--reporter.type=grpc"