FROM node:lts-slim
RUN mkdir /home/code
COPY app.js /home/code/
COPY entrypoint.sh /home/code/
WORKDIR /home/code
RUN apt -y update && \
    export PATH="$HOME/.local/bin:$PATH" && \
    apt install -y curl jq && \
    npm install --save uuid && \
    npm install --save pino && \
    npm install --save @opentelemetry/api && \
    npm install --save @opentelemetry/auto-instrumentations-node && \
    npm install --save @opentelemetry/sdk-trace-node && \
    npm install --save @opentelemetry/instrumentation-http && \
    apt -y autoremove && apt-get -y autoclean
# apt install -y dnsutils && \
# apt install -y util-linux && \
# apt install -y coreutils