apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-go-autogen-direct
  labels:
    app: cx-go-autogen-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-go-autogen-direct
  template:
    metadata:
      labels:
        app: cx-go-autogen-direct
    spec:
      containers:
        - name: cx-go-autogen-direct
          image: public.ecr.aws/w3s4j9x9/microservices-demo:go-autogen
          imagePullPolicy: Always
          env:
          - name: OTEL_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_SERVICE_NAME
            value: cx-go-autogen-direct
          - name: OTEL_RESOURCE_ATTRIBUTES
            value: cx.application.name=cx-go-autogen-direct,cx.subsystem.name=cx-go-autogen-direct
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: $(OTEL_IP):4317
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: grpc