---
# Flask Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-payment-gateway-flask
  namespace: default
spec:
  selector:
    matchLabels:
      name: cx-payment-gateway-flask
  template:
    metadata:
      labels:
        name: cx-payment-gateway-flask
    spec:
      containers:
      - name: cx-payment-gateway-flask
        image: public.ecr.aws/w3s4j9x9/microservices-demo:python
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        env:
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=cx-payment-gateway-flask, application.name=cx-payment-gateway-flask,api.name=cx-payment-gateway-flask,cx.application.name=cx-payment-gateway-flask,cx.subsystem.name=cx-payment-gateway-flask
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://$(OTEL_IP):4317
        - name: PYTHON_TEST_URLGOOD
          value: "BAD"
        - name: REDIS_SERVICE_HOST
          value: cx-redis
        command: ["/bin/sh"]
        args: ["start-flask-redis-otel.sh"]
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
