---
### Flask Server Service
apiVersion: v1
kind: Service
metadata:
  name: cx-payment-gateway-flask
spec:
  selector:
    app: cx-payment-gateway-flask
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
# Flask Server Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-payment-gateway-flask
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cx-payment-gateway-flask
  template:
    metadata:
      labels:
        app: cx-payment-gateway-flask
    spec:
      containers:
      - name: cx-payment-gateway-flask
        image: public.ecr.aws/w3s4j9x9/microservices-demo:python
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: OTEL_SERVICE_NAME
          value: cx-payment-gateway-flask
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-payment-gateway-flask,cx.subsystem.name=cx-payment-gateway-flask
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://$(OTEL_IP):4317
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: PYTHON_TEST_URLGOOD
          value: "GOOD"
        - name: REDIS_SERVICE_HOST
          value: cx-redis
        - name: REDIS_PASSWORD
          value: ""
        command: ["/bin/sh"]
        args: ["start-flask-redis-otel.sh"]
---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: cx-redis
spec:
  selector:
    app: cx-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-redis
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-redis
  template:
    metadata:
      labels:
        app: cx-redis
    spec:
      containers:
      - name: redis
        image: public.ecr.aws/w3s4j9x9/microservices-demo:redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 5
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
---
# Python Requests Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-shopping-cart-reqs
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cx-shopping-cart-reqs
  template:
    metadata:
      labels:
        app: cx-shopping-cart-reqs
    spec:
      containers:
      - name: cx-shopping-cart-reqs
        image: public.ecr.aws/w3s4j9x9/microservices-demo:python
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-shopping-cart-reqs
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-shopping-cart-reqs,cx.subsystem.name=cx-shopping-cart-reqs
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: PYTHON_TEST_URLGOOD
          value: "GOOD"
        - name: PYTHON_TEST_URL
          value: http://cx-payment-gateway-flask:5000
        - name: REDIS_PASSWORD
          value: ""
        command: ["/bin/sh"]
        args: ["start-reqs-envurl-otel.sh"]
