unset OTEL_EXPORTER_OTLP_ENDPOINT
unset OTEL_METRICS_EXPORTER
unset OTEL_TRACES_EXPORTER
unset OTEL_NODE_RESOURCE_DETECTORS
unset OTEL_EXPORTER_OTLP_ENDPOINT
unset OTEL_SERVICE_NAME
export OTEL_RESOURCE_ATTRIBUTES=service.name=cx-py-mssql,cx.application.name=cx-py-mssql,cx.subsystem.name=cx-py-mssql