extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  zpages:
    endpoint: 0.0.0.0:55679

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  filelog:
    include:
      - /var/log/*.log
      - /var/log/syslog
    start_at: beginning

  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      disk:
      load:
      filesystem:
      memory:
      network:
      paging:
      processes:
      process:

  prometheus:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']

  jmx:
    endpoint: "localhost:9999"
    jar_path: "/opt/opentelemetry-java-contrib-jmx-metrics.jar"
    target_system: "jvm"
    collection_interval: 10s

processors:
  batch:
  resourcedetection/env:
    detectors: ["system", "env"]
    system:
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: true
  resourcedetection/ec2:
    detectors: ["ec2"]
    ec2:
      resource_attributes:
        host.name:
          enabled: true
        host.id:
          enabled: true

exporters:
  debug:
    verbosity: detailed

  coralogix:
    domain: "cx498.coralogix.com"
    private_key: "cxtp_sIgP6mAHVL9MbM6ZfCjljTd5JMcMRN"
    application_name_attributes:
    - "service.namespace"
    subsystem_name_attributes:
    - "service.name"
    application_name: "workshop"
    subsystem_name: "monolith"
    timeout: 30s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/env, resourcedetection/ec2, batch]
      exporters: [coralogix]

    metrics:
      receivers: [otlp, prometheus, hostmetrics, jmx]
      processors: [resourcedetection/env, resourcedetection/ec2, batch]
      exporters: [coralogix]

    logs:
      receivers: [otlp, filelog]
      processors: [resourcedetection/env, resourcedetection/ec2, batch]
      exporters: [coralogix]

  extensions: [health_check, pprof, zpages]
