apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmx-metrics-pv
spec:
  capacity:
    storage: 64Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/jmx-metrics"
