apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jmx-metrics-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
  storageClassName: manual
  volumeName: jmx-metrics-pv 
