apiVersion: apps/v1
kind: Deployment
metadata:
  name: coraexp-mongo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coraexp-mongo
  template:
    metadata:
      labels:
        app: coraexp-mongo
    spec:
      containers:
      - name: mongo
        image: public.ecr.aws/w3s4j9x9/microservices-demo:coraexp-mongo
        imagePullPolicy: Always
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"

