apiVersion: v1
kind: Service
metadata:
  name: coraexp-postgres
spec:
  selector:
    app: coraexp-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP   # For internal access within the cluster