apiVersion: apps/v1
kind: Deployment
metadata:
  name: coraexp-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coraexp-postgres
  template:
    metadata:
      labels:
        app: coraexp-postgres
    spec:
      containers:
      - name: coraexp-postgres
        image: public.ecr.aws/w3s4j9x9/microservices-demo:coraexp-postgres   # Replace with your coraexp-postgresQL Docker image name
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: coraexp-postgres_DB
          value: "postgres"            # Replace with your database name
        - name: coraexp-postgres_USER
          value: "postgres"                # Replace with your database user
        - name: coraexp-postgres_PASSWORD
          value: "postgres"            # Replace with a secure password
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        # livenessProbe:
        #   exec:
        #     command: ["pg_isready", "-U", "my_user"]
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
        # readinessProbe:
        #   exec:
        #     command: ["pg_isready", "-U", "my_user"]
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
