FROM node:lts-bookworm
RUN mkdir /home/code
COPY . /home/code/
WORKDIR /home/code
RUN apt -y update && \
    export PATH="$HOME/.local/bin:$PATH" && \
    npm install --save @opentelemetry/api && \
    npm install --save @opentelemetry/auto-instrumentations-node && \
    npm install --save @opentelemetry/instrumentation-http && \
    apt -y autoremove && apt-get -y autoclean
# apt install -y curl
# apt install -y dnsutils && \
# apt install -y util-linux && \
# apt install -y coreutils