---
apiVersion: v1
kind: Service
metadata:
  name: cx-php-autogen
spec:
  selector:
    app: cx-php-autogen
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-php-autogen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-php-autogen
  template:
    metadata:
      labels:
        app: cx-php-autogen
    spec:
      containers:
        - name: cx-php-autogen
          image: public.ecr.aws/w3s4j9x9/microservices-demo:php-autogen-http
          imagePullPolicy: Always
          workingDir: /home/code
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OTEL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_SERVICE_NAME
              value: cx-php-autogen
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: cx.application.name=cx-php-autogen,cx.subsystem.name=cx-php-autogen
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_IP):4318
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: "true"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_PROPAGATORS
              value: "baggage,tracecontext"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"