---
apiVersion: v1
kind: Service
metadata:
  name: cx-php-server
spec:
  selector:
    app: cx-php-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-php-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-php-server
  template:
    metadata:
      labels:
        app: cx-php-server
    spec:
      containers:
        - name: cx-php-server
          image: public.ecr.aws/w3s4j9x9/microservices-demo:php-autogen-http
          imagePullPolicy: Always
          workingDir: /home/code
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: OTEL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_SERVICE_NAME
              value: cx-php-server
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: cx.application.name=cx-php-server,cx.subsystem.name=cx-php-server
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(OTEL_IP):4318
            - name: OTEL_PHP_AUTOLOAD_ENABLED
              value: "true"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_PROPAGATORS
              value: "baggage,tracecontext"
            - name: OTEL_METRICS_EXPORTER
              value: "none"
            - name: OTEL_LOGS_EXPORTER
              value: "none"
          command: ["php", "-S", "0.0.0.0:8080", "-t", "/home/code"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cx-php-client
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cx-php-client
  template:
    metadata:
      labels:
        app: cx-php-client
    spec:
      containers:
      - name: cx-php-client
        image: public.ecr.aws/w3s4j9x9/microservices-demo:php-autogen-http
        imagePullPolicy: Always
        workingDir: /home/code
        ports:
          - name: http
            containerPort: 8080
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: cx-php-client
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=cx-php-client,cx.subsystem.name=cx-php-client
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4318
        - name: OTEL_PHP_AUTOLOAD_ENABLED
          value: "true"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        - name: OTEL_PROPAGATORS
          value: "baggage,tracecontext"
        - name: OTEL_METRICS_EXPORTER
          value: "none"
        - name: OTEL_LOGS_EXPORTER
          value: "none"
        # test if needed
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
