---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-autogen
  namespace: default
spec:
  selector:
    matchLabels:
      name: java-autogen
  template:
    metadata:
      labels:
        name: java-autogen
    spec:
      containers:
      - name: java-autogen
        image: public.ecr.aws/w3s4j9x9/microservices-demo:java
        imagePullPolicy: Always
        workingDir: /home/code
        env:
        - name: OTEL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_SERVICE_NAME
          value: java-autogen
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: cx.application.name=java-autogen,cx.subsystem.name=java-autogen
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_IP):4317
        - name: JAVA_TEST_URL
          value: https://www.bing.com
        command: ["/bin/sh"]
        args: ["run-client.sh"]
        # test if needed
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]